[Keymap]
;ScreenNum = A, B, C, D, F, G, H, I

000 =  1, 2, 9, 9, 9, 9, 9, 9

020  = 1, 2, 3, 4, 9, 9, 9, 9
014  = 1, 2, 3, 4, 9, 9, 9, 9
052  = 1, 2, 3, 9, 9, 9, 9, 9
040  = 5, 6, 7, 8, 1, 2, 3, 4

042  = 1, 2, 9, 9, 9, 9, 9, 9
070  = 1, 2, 3, 9, 9, 9, 9, 9
080  = 1, 2, 3, 9, 9, 9, 9, 9
095  = 1, 2, 3, 9, 9, 9, 9, 9

451  = 1, 2, 3, 9, 9, 9, 9, 9

046  = 1, 2, 3, 8, 4, 5, 6, 7
055  = 9, 9, 9, 9, 2, 1, 9, 9
090  = 9, 9, 9, 4, 9, 3, 2, 1
100  = 9, 9, 9, 4, 9, 3, 2, 1
110 = 9, 9, 9, 4, 9, 3, 2, 1
111 = 9, 9, 9, 4, 9, 3, 2, 1

137 = 9, 1, 2, 9, 9, 9, 9, 9
025 = 1, 2, 3, 4, 9, 9, 9, 9
026 = 1, 2, 3, 4, 9, 9, 9, 9
029 = 1, 2, 3, 9, 9, 9, 9, 9
074 = 9, 1, 2, 3, 4, 9, 9, 9
166 = 9, 1, 2, 3, 4, 9, 9, 9
030 = 1, 2, 9, 9, 9, 9, 9, 9
970 = 1, 2, 9, 9, 9, 9, 9, 9
034 = 1, 2, 3, 4, 9, 9, 9, 9
300 = 1, 2, 9, 9, 9, 9, 9, 9
310 = 1, 2, 3, 4, 9, 9, 9, 9
032 = 1, 2, 3, 9, 9, 9, 9, 9
113 = 9, 9, 1, 2, 9, 9, 9, 9
072 = 9, 1, 2, 9, 9, 9, 9, 9
032 = 1, 2, 9, 9, 9, 9, 9, 9
122 = 9, 9, 1, 2, 9, 9, 9, 9

[Speech]
EnableBalanceFormat=1
;SleepResult=6

EngineCount=2
Engine1 = Microsoft Sam
Engine2 = Cepstral Miguel

Rate = 0
Volume = 80
VolumeOffset = 10

; default is 2 the sleep time when to repeat to speech
RepeatWaitTime =2

;defualt is 1 the time sleep when the text was inserted 
InsertTextWaitTime=1

; default is 4 wait when speech input key message
SleepKey = 1

; default is 5
SleepRemoveCash = 1

; default is 6
SleepRemoveReceipt = 1

; default is 12
SleepResult = 1

; default is 15
SleepRemoveHeadset = 1

EnableVerification=0
[RepalceString]
;some abbreviate word can't read by engine so must replace
;the void string Replace the string in include of subscreen
;the count of string replace group
ReplaceCount =2

;the old key string repalce resoure string
ReplaceOldKey1=CNY
;the new key string repacle to dest string
ReplaceNewKey1=C N Y
ReplaceOldKey2=URL
ReplaceNewKey2=U R L

[BalanceFormat_1]
;Precondition = 0
;FORMAT = 'Available balance:'
;SaveTo = 3100
;Replaceto = AVAILABLE BALANCE is 
;DelaySecond = 3

Precondition = 0
FORMAT = AVAILABLE:
Replaceto = Available balance is
DelaySecond = 5

[ABCD]
V_Part_AMT_1=withdra
V_Part_ACC_From_1=
V_Part_ACC_To_1=
V_Part_Receipt_1=
Verification_1=
start=0
Length=7
FullMatch=1
Decimallen=2